# Generated by Django 4.1 on 2022-08-14 17:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_category_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('image', models.ImageField(upload_to='product', verbose_name='تصویر')),
                ('available', models.BooleanField(default=True, verbose_name='موجود است؟')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('information', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='اطلاعات')),
                ('status', models.CharField(blank=True, choices=[('None', 'none'), ('Size', 'size')], max_length=50, null=True, verbose_name='ویژگی')),
                ('total_favourite', models.PositiveIntegerField(default=0)),
                ('sell', models.PositiveIntegerField(default=0)),
                ('num_view', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(blank=True, to='home.category', verbose_name='دسته بندی')),
                ('favourite', models.ManyToManyField(blank=True, related_name='fa_user', to=settings.AUTH_USER_MODEL, verbose_name='علاقه مندی')),
                ('like', models.ManyToManyField(blank=True, related_name='product_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='اسم')),
            ],
            options={
                'verbose_name': 'سایز محصول',
                'verbose_name_plural': 'سایز محصولات',
            },
        ),
        migrations.CreateModel(
            name='Variantproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت اصلی')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='home.product', verbose_name='ویژگی محصول')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='home.size', verbose_name='اندازه'),
        ),
        migrations.AddField(
            model_name='product',
            name='unlike',
            field=models.ManyToManyField(blank=True, related_name='product_unlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='product_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
