# Generated by Django 4.1 on 2022-08-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_size_variantproduct_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproduct',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='size_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Variantproduct',
        ),
    ]
