# Generated by Django 4.1 on 2022-08-16 04:19

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shahr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='shahr/')),
                ('mahsool', models.ManyToManyField(blank=True, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='shahr/')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.IntegerField(blank=True)),
                ('start', django_jalali.db.models.jDateTimeField()),
                ('end', django_jalali.db.models.jDateTimeField()),
                ('mahsool', models.ManyToManyField(blank=True, to='home.product')),
                ('shahr', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.shahr')),
            ],
        ),
    ]
