# Generated by Django 4.1 on 2022-08-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shahr_shobe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shahr',
            name='mahsool',
        ),
    ]
