# Generated by Django 4.1 on 2022-08-16 05:10

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_shahr_mahsool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shobe',
            name='end',
            field=django_jalali.db.models.jDateTimeField(default='09:39:43'),
        ),
        migrations.AlterField(
            model_name='shobe',
            name='start',
            field=django_jalali.db.models.jDateTimeField(default='09:39:43'),
        ),
    ]
