# Generated by Django 4.1 on 2022-08-16 05:14

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_shobe_end_alter_shobe_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shobe',
            name='end',
            field=django_jalali.db.models.jDateTimeField(verbose_name=datetime.datetime(2022, 8, 16, 9, 44, 54, 887813)),
        ),
        migrations.AlterField(
            model_name='shobe',
            name='start',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
