# Generated by Django 4.1 on 2022-08-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_shobe_end_alter_shobe_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shobe',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shobe',
            name='start',
            field=models.TimeField(),
        ),
    ]
