# Generated by Django 4.1 on 2022-08-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_shobe_end_alter_shobe_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shobe',
            name='image',
            field=models.ImageField(blank=True, upload_to='shobe/'),
        ),
    ]
