# Generated by Django 4.1 on 2022-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_shobe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shobe',
            name='mahsool',
            field=models.ManyToManyField(blank=True, related_name='sh', to='home.product'),
        ),
    ]
