# Generated by Django 4.1 on 2022-08-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ersalorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ersalorder',
            old_name='name',
            new_name='ersal',
        ),
    ]
