# Generated by Django 4.1 on 2022-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_ersal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='information',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
