# Generated by Django 4.1 on 2022-08-14 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='formprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='شماره همراه')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('profile_image', models.ImageField(blank=True, default='', null=True, upload_to='profile/', verbose_name='عکس پروفایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userp', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها ',
            },
        ),
    ]
