# Generated by Django 4.1 on 2022-08-14 12:16

from django.conf import settings
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_formprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='کد تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='آیا فعال است؟')),
                ('start', django_jalali.db.models.jDateTimeField(verbose_name='شروع')),
                ('end', django_jalali.db.models.jDateTimeField(verbose_name='پایان')),
                ('discount', models.IntegerField(verbose_name='درصد تخفیف')),
                ('dastresi', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
